require("dotenv").config();

const {
	PORT,
	DB_PASSWORD,
	SESSION_SECRET,
	MAILER_EMAIL,
	MAILER_PASS,
	TWILIO_SID,
	TWILIO_PHONE,
	TWILIO_TOKEN,
	ADMIN_PHONE,
} = process.env;
module.exports = {
	PORT,
	DB_PASSWORD,
	SESSION_SECRET,
	MAILER_EMAIL: MAILER_EMAIL,
	ADMIN_PHONE: ADMIN_PHONE,
	MAILER_PASS: MAILER_PASS,
	TWILIO_PHONE: TWILIO_PHONE,
	TWILIO_SID: TWILIO_SID,
	TWILIO_TOKEN: TWILIO_TOKEN,
};
